### ISSUE TITLE
Crashes if pagesCommitIdUrl is incorrect

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/Fronter.NET#30]
If the URL isn't found, the whole fronter just closes. Instead it should just log an error.

**Comment by IhateTrains** [comment]
Do you remember what URL caused the crash? I'm getting a warning instead of crash after adding an 's' to the URL, but it may depend on the error code the server returns.
![image](https://user-images.githubusercontent.com/29546927/168491374-4c4f4f82-eea4-4a2d-9d0b-ec25fc5e4845.png)

**Comment by Idhrendur** [comment]
Oh, huh, it's actually https://paradoxgameconverters.com/commit_ids/Vic3ToHoI4.txt, though that's completely incorrect for https://github.com/ParadoxGameConverters/HoI4MapDrawer (where I'm now using the new fronter).

**Comment by Idhrendur** [comment]
Triggered by this build: https://github.com/ParadoxGameConverters/HoI4MapDrawer/commit/5c236576c09fe49f29274a9514000de4728f22bd
